//
//
// I NEED TO ADD AN EVENTLISTENER FOR CLICK
// EACH PLAYER WILL HAVE A KEY TO PRESS TO MAKE THE OBJECT MOVE
// PROBABLY WILL USE THE KEYUP
//
// I NEED A FUNCTION SO THAT EACH PLAYER CAN MOVE THERE OBJECT WITH EACH CLICK
// I NEED A FUNCTION TO RESET THE GAME
// I NEED A FUNCTION TO START THE GAME??MAYBE IT IS ALREADY IN THE CLASS OF EACH PLAYER WITH THE ORIGINAL POSTION THEY ARE IN

alert("JS CONNECTED");
